### ISSUE TITLE
Using JNA instead of re-writing code

### ISSUE THREAD

**Issue by nemo83** [spotify/annoy-java#12]
Hi,

is there any reason why you guys are rewriting the code in java instead of using JNA as it has been done for [annoy4s](https://github.com/annoy4s/annoy4s)?

**Comment by a1k0n** [comment]
Pretty sure using JNI is the plan.  https://github.com/yonromai/annoy-java/tree/v0.4.2
ping @yonromai 

The reason? When this was originally written, annoy was a python library and wasn't factored into a reusable C++ library, and, I don't know, I kind of wanted to prove it could be done in pure Java because @erikbern said it couldn't. :)

**Comment by yonromai** [comment]
The java implementation has worked fine for a while, although it's getting annoying to keep java's codebase aligned with the C++ one. (poor pun intended..)
The plan is indeed to move to a native binding solution, although there might be some problems with JNI's GPL license.
